name: Selenium Script

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  run_script:
    runs-on: ubuntu-latest  # Choose your operating system
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Choose your Python version
        
    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Selenium Script
      run: |
        python x.py  # Replace with your script file name
